apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app: postgres
data:
  PGHOST: postgres
  PGPORT: "5432"
  PGUSER: postgres
  PGDATABASE: postgres
  PGPASSWORD: postgres
  PGDATA: /var/lib/postgresql/data
