# Deploy this first to see the pod gated from being schedule
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      annotations:
        k8s.ksgate.org/postgres-config: |
          {
            "kind": "ConfigMap",
            "name": "postgres-config"
          }
        k8s.ksgate.org/postgres-deployment: |
          {
            "apiVersion": "apps/v1",
            "kind": "Deployment",
            "name": "postgres",
            "expression": "resource.status.readyReplicas >= 1"
          }
        k8s.ksgate.org/postgres-service: |
          {
            "kind": "Service",
            "name": "postgres"
          }
      labels:
        app: my-app
    spec:
      schedulingGates:
      - name: k8s.ksgate.org/postgres-config
      - name: k8s.ksgate.org/postgres-deployment
      - name: k8s.ksgate.org/postgres-service
      containers:
      - name: my-app
        image: alpine/psql:latest
        command:
        - sh
        - -c
        - |
          cleanup()
          {
            echo "Recieved signal to exit"
            exit 0
          }
          trap cleanup SIGTERM SIGINT
          while true; do
            date +%s
            psql -c "SELECT 1 as SUCCESS"
            sleep 5
          done
        envFrom:
        - configMapRef:
            name: postgres-config
        resources: {}

