# Deploy this after the pod to see the pod scheduled

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      annotations:
        k8s.ksgate.org/postgres-config: |
          {
            "apiVersion": "v1",
            "kind": "ConfigMap",
            "name": "postgres-config"
          }
        k8s.ksgate.org/postgres-pv: |
          {
            "apiVersion": "v1",
            "kind": "PersistentVolume",
            "name": "postgres-pv"
          }
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        envFrom:
        - configMapRef:
            name: postgres-config
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", $(POSTGRES_USER)]
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", $(POSTGRES_USER)]
        ports:
        - containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      schedulingGates:
      - name: k8s.ksgate.org/postgres-config
      - name: k8s.ksgate.org/postgres-pv
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
