name: 'Execute E2E Tests'
description: 'Execute E2E tests'
runs:
  using: "composite"
  steps:
  - name: Install the latest version of kind
    run: |
      curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
      chmod +x ./kind
      sudo mv ./kind /usr/local/bin/kind

  - name: Verify kind installation
    run: |
      kind version

  - name: Create kind cluster
    run: |
      kind create cluster

  - name: Running E2E Tests
    run: |
      make test-e2e
